title: 'Demo Lamp on AWS'
type: free
description: 'Demo Lamp on AWS using Bitnami image.'
cloud_provider: aws
build_engine: terraform
available_regions:
    - sa-east-1
    - eu-west-3
    - eu-west-2
    - eu-west-1
    - eu-central-1
    - ca-central-1
    - ap-northeast-1
    - ap-southeast-2
    - ap-southeast-1
    - ap-northeast-2
    - ap-south-1
    - us-west-2
    - us-west-1
    - us-east-2
    - us-east-1
image: 'https://assets.artifakt.io/lamp.png'
category: cms
main_language: php
licence:
    code: mit
    name: MIT
tags:
    - Lamp
    - AWS
    - bitnami
    - demo
    - cms
infrastructure:
    diagram: 'https://assets.artifakt.io/artifact-demo-app-aws.png'
    build_time: 50
    cost_estimation:
        monthly_price: 18.3
        details: 'Price calculated using t2.small instance and 8GB HDD in Ireland.'
outputs:
    -
        code: public_url
        name: 'public URL'
        description: 'Fully qualified URL'
        category: url
